### ISSUE TITLE
Pre-commit check fails because TypeError: 'FileSystem' object is not iterable

### ISSUE THREAD

**Issue by lazigu** [tlambert03/napari-plugin-checks#7]
Hi Talley,

Recently I noticed that the pre-commit [test of napari-plugin-check was randomly failing](https://github.com/BiAPoL/napari-clusters-plotter/pull/127), and I couldn't figure out where is the problem. Therefore, for now, I had to remove this hook in order not to have failing tests. I hope you can help to determine the problem, which might be on my side or related to some other package, but I am just bad at reading this error.

Here is the error traceback:

```
napari-plugin-checks.....................................................Failed
- hook id: napari-plugin-checks
- exit code: 1

Traceback (most recent call last):
  File "/pc/clone/iswaKIRuSpC2mXd0GYpAUg/py_env-python3/bin/napari-plugin-check", line 8, in <module>
    sys.exit(main())
  File "/pc/clone/iswaKIRuSpC2mXd0GYpAUg/py_env-python3/lib/python3.10/site-packages/napari_plugin_checks.py", line 153, in main
    return sum(check_file(filename) for filename in args.filenames)
  File "/pc/clone/iswaKIRuSpC2mXd0GYpAUg/py_env-python3/lib/python3.10/site-packages/napari_plugin_checks.py", line 153, in <genexpr>
    return sum(check_file(filename) for filename in args.filenames)
  File "/pc/clone/iswaKIRuSpC2mXd0GYpAUg/py_env-python3/lib/python3.10/site-packages/napari_plugin_checks.py", line 131, in check_file
    return function(filename)
  File "/pc/clone/iswaKIRuSpC2mXd0GYpAUg/py_env-python3/lib/python3.10/site-packages/napari_plugin_checks.py", line 99, in check_py
    return _check_imports(fname)
  File "/pc/clone/iswaKIRuSpC2mXd0GYpAUg/py_env-python3/lib/python3.10/site-packages/napari_plugin_checks.py", line 112, in _check_imports
    scanner = importscanner.ImportScanner({root: {module}}, fs, True)
  File "/pc/clone/iswaKIRuSpC2mXd0GYpAUg/py_env-python3/lib/python3.10/site-packages/grimp/application/ports/importscanner.py", line 35, in __init__
    for package in self.found_packages:
TypeError: 'FileSystem' object is not iterable
Traceback (most recent call last):
  File "/pc/clone/iswaKIRuSpC2mXd0GYpAUg/py_env-python3/bin/napari-plugin-check", line 8, in <module>
    sys.exit(main())
  File "/pc/clone/iswaKIRuSpC2mXd0GYpAUg/py_env-python3/lib/python3.10/site-packages/napari_plugin_checks.py", line 153, in main
    return sum(check_file(filename) for filename in args.filenames)
  File "/pc/clone/iswaKIRuSpC2mXd0GYpAUg/py_env-python3/lib/python3.10/site-packages/napari_plugin_checks.py", line 153, in <genexpr>
    return sum(check_file(filename) for filename in args.filenames)
  File "/pc/clone/iswaKIRuSpC2mXd0GYpAUg/py_env-python3/lib/python3.10/site-packages/napari_plugin_checks.py", line 131, in check_file
    return function(filename)
  File "/pc/clone/iswaKIRuSpC2mXd0GYpAUg/py_env-python3/lib/python3.10/site-packages/napari_plugin_checks.py", line 99, in check_py
    return _check_imports(fname)
  File "/pc/clone/iswaKIRuSpC2mXd0GYpAUg/py_env-python3/lib/python3.10/site-packages/napari_plugin_checks.py", line 112, in _check_imports
    scanner = importscanner.ImportScanner({root: {module}}, fs, True)
  File "/pc/clone/iswaKIRuSpC2mXd0GYpAUg/py_env-python3/lib/python3.10/site-packages/grimp/application/ports/importscanner.py", line 35, in __init__
    for package in self.found_packages:
TypeError: 'FileSystem' object is not iterable
```

**Comment by tlambert03** [comment]
Thanks for the heads up!  Will have a look

(And sorry for the inconvenience)

**Comment by tlambert03** [comment]
Should be fixed now with #6

if you'd like to re-enabling it, please bump your pre-commit rev to v0.3.0

```yaml
-   repo: https://github.com/tlambert03/napari-plugin-checks
    rev: v0.3.0
    hooks:
    - id: napari-plugin-checks
```

**Comment by tlambert03** [comment]
by the way: this was cause by an API breakage in the recent release of [grimp](https://pypi.org/project/grimp/) (the only dependency of this pre-commit hook).  I've hard pinned grimp (and will pin any other deps going forward) so this shouldn't happen unexpectedly again.  thanks again for the report

**Comment by lazigu** [comment]
Thanks a lot for such a quick fix!
